### ISSUE TITLE
Pointfree does not like UnicodeSyntax.

### ISSUE THREAD

**Issue by isturdy** [bmillwood/pointfree#4]
Produced with `pointfree "(\n -> (return 0) ± (return $ sqrt n))"`.

This is probably not critical, as substituting an arbitrary non-unicode infix operator should produce the same result, unless precedence is relevant.

**Comment by subttle** [comment]
Hi, thank you so much for this awesome project. It's been one of my favorite Haskell tools for a long time! I apologize for commenting on an old ticket, perhaps I should make a new one as this is not exactly the same request, regardless I'll just ask my question here for now. Would it be possible at this point to try supporting some minimal unicode syntax characters starting with even just `→`? This would be really handy for those of us working with lambda functions while using the `UnicodeSyntax` [extension](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/exts/unicode_syntax.html). I would completely understand if you don't want to support this, but I figure it is worth politely requesting to see if it is now reasonably doable given the several years it has been since the original request. I hope you have a nice day. Thank you for your time and consideration!

**Comment by bmillwood** [comment]
I enabled UnicodeSyntax in the parser in revision 5cab0d05d3874b85f038bb2a320c86885c26e77e
